import RootStyleRegistry from "./emotion";

export const metadata = {
  title: "NextJS App Router task",
  description: "Generated by create next app",
};

import Main from './main';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <RootStyleRegistry>
          <Main>{children}</Main>
        </RootStyleRegistry>
      </body>
    </html>
  );
}
